# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/new-new-new',
                'doc_host': 'https://anasbraj.github.io',
                'git_url': 'https://github.com/anasbraj/new-new-new',
                'lib_path': 'new_new_new'},
  'syms': {'new_new_new.core': {'new_new_new.core.foo': ('core.html#foo', 'new_new_new/core.py')}}}
